name: CI - SAST Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep (auto rules) and save JSON
        run: |
          semgrep --config auto --json --output semgrep-report.json || true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Fail if critical findings (optional)
        run: |
          if jq -e '.results[] | select(.severity=="CRITICAL")' semgrep-report.json > /dev/null 2>&1; then
            echo "Critical issue(s) found by Semgrep. Failing the job."
            jq '.results[] | {path: .path, start: .start, check_id: .check_id, severity: .severity, message: .extra.message}' semgrep-report.json
            exit 1
          else
            echo "No critical issues found."
          fi
        env:
          TZ: UTC
